#!/bin/bash
#PBS -N GINO
#PBS -l select=1:ncpus=4:mem=46gb:ngpus=1
#PBS -l walltime=24:00:00
#PBS -m abe
#PBS -j oe
#PBS -o /srv/scratch/z5370003/projects/04_groundwater/variable_density/logs/train_gino.log


# Change to the directory from which the job was submitted
cd $PBS_O_WORKDIR/..

# Run the Python script
/srv/scratch/z5370003/miniconda3/envs/torch-env/bin/python train_gino_on_patches.py --n_epochs 10
